### ISSUE TITLE
Segmented rendered multiline

### ISSUE THREAD

**Issue by norbdev** [creageek/segmented#3]
I needed to add `android:orientation="horizontal"` on Android 5.0

**Comment by creageek** [comment]
Hi, could you please provide more info about what exactly you are trying to achieve? 
Some screenshots would be handy as well :)

**Comment by creageek** [comment]
Hi, @norbdev!

But there's a support of `android:orientation="horizontal"`. It just does not set by default for some reason. You can refer to the sample app: https://github.com/creageek/segmented/blob/master/sample/src/main/res/layout/activity_main.xml
